services:
  redis:
    image: redis:7-alpine
    restart: always
    container_name: manga-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  scrap2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    working_dir: /app
    container_name: scrap2
    command: python /app/app.py
    ports:
      - 8889:8889
    depends_on:
      - redis

volumes:
  redis_data: