services:
  scrap2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    working_dir: /app
    container_name: scrap2
    command: python /app/app.py
    ports:
      - 8889:8889